workflows:
  android-launcher:
    name: iOS Launcher Android
    environment:
      groups:
        - keystore_credentials
    scripts:
      - name: Fix Gradle Permissions
        script: |
          chmod +x ./gradlew
          ls -la gradlew
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - developer@example.com
